
// This file has been generated by the GUI designer. Do not modify.
namespace guiTesting
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action exitAction;

		private global::Gtk.Action fileAction;

		private global::Gtk.Action exitAction1;

		private global::Gtk.Action cutAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget guiTesting.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.exitAction = new global::Gtk.Action ("exitAction", global::Mono.Unix.Catalog.GetString ("exit"), null, null);
			this.exitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("exit");
			w1.Add (this.exitAction, null);
			this.fileAction = new global::Gtk.Action ("fileAction", global::Mono.Unix.Catalog.GetString ("file"), null, null);
			this.fileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("file");
			w1.Add (this.fileAction, null);
			this.exitAction1 = new global::Gtk.Action ("exitAction1", global::Mono.Unix.Catalog.GetString ("exit"), null, null);
			this.exitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("exit");
			w1.Add (this.exitAction1, null);
			this.cutAction = new global::Gtk.Action ("cutAction", global::Mono.Unix.Catalog.GetString ("open"), null, "gtk-cut");
			this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("open");
			w1.Add (this.cutAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "guiTesting.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child guiTesting.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='fileAction' action='fileAction'><menuitem name='exitAction1' action='exitAction1'/><menuitem name='cutAction' action='cutAction'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add (this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.exitAction1.Activated += new global::System.EventHandler (this.exit);
			this.cutAction.Activated += new global::System.EventHandler (this.@new);
		}
	}
}
